/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_objectserver_session_Session */

#ifndef _Included_io_realm_objectserver_session_Session
#define _Included_io_realm_objectserver_session_Session
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_objectserver_session_Session
 * Method:    nativeCreateSession
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_objectserver_session_Session_nativeCreateSession
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_realm_objectserver_session_Session
 * Method:    nativeBind
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_objectserver_session_Session_nativeBind
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     io_realm_objectserver_session_Session
 * Method:    nativeUnbind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_objectserver_session_Session_nativeUnbind
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_objectserver_session_Session
 * Method:    nativeRefresh
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_objectserver_session_Session_nativeRefresh
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
