/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_BatchDeleter */

#ifndef _Included_io_realm_internal_BatchDeleter
#define _Included_io_realm_internal_BatchDeleter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_BatchDeleter
 * Method:    deleteNativePointers
 * Signature: ([J[J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_BatchDeleter_deleteNativePointers
  (JNIEnv *, jclass, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
