/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_RealmConfiguration */

#ifndef _Included_io_realm_RealmConfiguration
#define _Included_io_realm_RealmConfiguration
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_RealmConfiguration_KEY_LENGTH
#define io_realm_RealmConfiguration_KEY_LENGTH 64L
/*
 * Class:     io_realm_RealmConfiguration
 * Method:    createConfigurationPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_RealmConfiguration_createConfigurationPointer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
