/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_objectserver_SyncManager */

#ifndef _Included_io_realm_objectserver_SyncManager
#define _Included_io_realm_objectserver_SyncManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_objectserver_SyncManager
 * Method:    nativeCreateClient
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_realm_objectserver_SyncManager_nativeCreateClient
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
