/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_io_realm_objectserver_Session
#define _Included_io_realm_objectserver_Session
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_io_realm_objectserver_Session_nativeCreateSession
  (JNIEnv *, jclass, jlong, jstring);

JNIEXPORT void JNICALL Java_io_realm_objectserver_Session_nativeBind
  (JNIEnv *, jclass, jlong, jstring, jstring);

JNIEXPORT void JNICALL Java_io_realm_objectserver_Session_nativeUnbind
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_io_realm_objectserver_Session_nativeRefresh
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
