/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_NativeObjectReference */

#ifndef _Included_io_realm_internal_NativeObjectReference
#define _Included_io_realm_internal_NativeObjectReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_NativeObjectReference
 * Method:    nativeCleanUp
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_NativeObjectReference_nativeCleanUp
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
