lib_LIBRARIES = librealm-jni.a

JNI_SOURCES := $(wildcard *.cpp object-store/*.cpp object-store/impl/*.cpp object-store/impl/android/*.cpp)
librealm_jni_a_SOURCES = $(JNI_SOURCES)

include ../generic.mk
