INSTALL_PREFIX      = auto
JAVA_COMMAND        = /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/bin/java
JAVAC_COMMAND       = /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/bin/javac
JAVA_VERSION        = 1.7.0_51
JAVA_CFLAGS         = -I/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/include/darwin
REQUIRED_JARS       = /usr/local/share/java/commons-io.jar /usr/local/share/java/commons-lang.jar /usr/local/share/java/freemarker.jar
TESTING_JARS        = /usr/local/share/java/testng.jar /usr/local/share/java/qdox.jar /usr/local/share/java/bsh.jar
JNI_INSTALL_DIR     = /Library/Java/Extensions
JAR_INSTALL_DIR     = /usr/local/share/java
JNI_SUFFIX          = .jnilib
TIGHTDB_CONFIG      = /usr/local/bin/tightdb-config
TIGHTDB_VERSION     = 0.1.6
TIGHTDB_CFLAGS      = -I/usr/local/include -DTIGHTDB_HAVE_CONFIG
TIGHTDB_CFLAGS_DBG  = -I/usr/local/include -DTIGHTDB_HAVE_CONFIG -DTIGHTDB_DEBUG
TIGHTDB_LDFLAGS     = -L/usr/local/lib -Wl,-rpath,/usr/local/lib -ltightdb
TIGHTDB_LDFLAGS_DBG = -L/usr/local/lib -Wl,-rpath,/usr/local/lib -ltightdb-dbg
ANDROID_NDK_HOME    = /usr/local/Cellar/android-ndk/r9c
ANDROID_CORE_LIB    = /Users/rasmus/Documents/code/tightdb/android-lib
