call starttest CursorColumnsTest
call starttest GroupTest
call starttest SubtableTest
call starttest TableColumnsTest
call starttest TableDataOperationsTest
call starttest TableNavigationTest
call starttest TableQueryTest
call starttest TableTest
call starttest ViewColumnsTest
call starttest ViewDataOperationsTest
call starttest ViewNavigationTest
call starttest JNISubtableTest
call starttest JNITableSpecTest
call starttest JNIViewSearchTest
