/*
 * Copyright 2014 Realm Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.realm.internal.modules;

import java.util.Set;

import io.realm.RealmObject;
import io.realm.internal.RealmProxyMediator;

/**
 * Abstract class for defining a set of RealmObject classes, called a module. A Realm can know about one or more
 * modules, so modules can be used to assign classes to specific Realms. This can be used by
 * libraries to expose their RealmObjects or restrict a Realm to only a subset of the RealmObjects, which can make
 * them easier to maintain.
 *
 * Realm always generate a DefaultRealmModule consisting of all known RealmObjects and
 * this module is used as default if nothing else is specified.

 * Library projects <bold>must</bold> use explicit modules in order to not conflict with app code.
 *
 * @see io.realm.annotations.internal.RealmModule
 */
public abstract class RealmClassCollection {

    /**
     * Returns the {@link io.realm.internal.RealmProxyMediator} that can handle the classes returned by
     * {@link #getModuleClasses()}. This method is auto generated by the annotation processor.
     * @return RealmProxyMediator that
     */
    public RealmProxyMediator getProxyMediator() {
        // Noop, only implemented here so user modules don't have to, but so our Binders can override as well
        return null;
    }

    /**
     * Returns the set of classes that are part of this module.
     *
     * @return The classes that are part of this module.
     */
    public abstract Set<Class<? extends RealmObject>> getModuleClasses();
}
