/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_Row */

#ifndef _Included_io_realm_internal_Row
#define _Included_io_realm_internal_Row
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetColumnCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Row_nativeGetColumnCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetColumnName
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Row_nativeGetColumnName
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetColumnIndex
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Row_nativeGetColumnIndex
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetColumnType
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_realm_internal_Row_nativeGetColumnType
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetIndex
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Row_nativeGetIndex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetLong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Row_nativeGetLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetBoolean
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Row_nativeGetBoolean
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetFloat
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_io_realm_internal_Row_nativeGetFloat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetDouble
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_io_realm_internal_Row_nativeGetDouble
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetDateTime
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Row_nativeGetDateTime
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetString
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Row_nativeGetString
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetByteArray
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_realm_internal_Row_nativeGetByteArray
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetMixedType
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_realm_internal_Row_nativeGetMixedType
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetMixed
 * Signature: (JJ)Lio/realm/internal/Mixed;
 */
JNIEXPORT jobject JNICALL Java_io_realm_internal_Row_nativeGetMixed
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetLink
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Row_nativeGetLink
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeIsNullLink
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Row_nativeIsNullLink
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeGetLinkView
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Row_nativeGetLinkView
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeSetLong
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeSetLong
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeSetBoolean
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeSetBoolean
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeSetFloat
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeSetFloat
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeSetDouble
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeSetDouble
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeSetDate
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeSetDate
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeSetString
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeSetString
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeSetByteArray
 * Signature: (JJ[B)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeSetByteArray
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeSetMixed
 * Signature: (JJLio/realm/internal/Mixed;)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeSetMixed
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeSetLink
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeSetLink
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeNullifyLink
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeNullifyLink
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Row_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Row
 * Method:    nativeIsAttached
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Row_nativeIsAttached
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
