/* This file was automatically generated by TightDB. */
package com.tightdb.test;

import com.tightdb.*;
import com.tightdb.lib.*;

/**
 * This class represents a TightDB view and was automatically generated.
 */
public class TestEmployeeView extends AbstractView<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery> {

	public final StringRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery> firstName = new StringRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery>(TestEmployeeTable.TYPES, rowset, 0, "firstName");
	public final StringRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery> lastName = new StringRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery>(TestEmployeeTable.TYPES, rowset, 1, "lastName");
	public final LongRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery> salary = new LongRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery>(TestEmployeeTable.TYPES, rowset, 2, "salary");
	public final BooleanRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery> driver = new BooleanRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery>(TestEmployeeTable.TYPES, rowset, 3, "driver");
	public final BinaryRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery> photo = new BinaryRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery>(TestEmployeeTable.TYPES, rowset, 4, "photo");
	public final DateRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery> birthdate = new DateRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery>(TestEmployeeTable.TYPES, rowset, 5, "birthdate");
	public final MixedRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery> extra = new MixedRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery>(TestEmployeeTable.TYPES, rowset, 6, "extra");
	public final TableRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery, TestPhoneTable> phones = new TableRowsetColumn<TestEmployeeRow, TestEmployeeView, TestEmployeeQuery, TestPhoneTable>(TestEmployeeTable.TYPES, rowset, 7, "phones", TestPhoneTable.class);
	public TestEmployeeView(TableViewBase viewBase) {
		super(TestEmployeeTable.TYPES, viewBase);
	}

}
