/* This file was automatically generated by TightDB. */
package com.tightdb.test;

import com.tightdb.*;
import com.tightdb.lib.*;

/**
 * This class represents a TightDB view and was automatically generated.
 */
public class TestPhoneView extends AbstractView<TestPhoneRow, TestPhoneView, TestPhoneQuery> {

	public final StringRowsetColumn<TestPhoneRow, TestPhoneView, TestPhoneQuery> type = new StringRowsetColumn<TestPhoneRow, TestPhoneView, TestPhoneQuery>(TestPhoneTable.TYPES, rowset, 0, "type");
	public final StringRowsetColumn<TestPhoneRow, TestPhoneView, TestPhoneQuery> number = new StringRowsetColumn<TestPhoneRow, TestPhoneView, TestPhoneQuery>(TestPhoneTable.TYPES, rowset, 1, "number");
	public TestPhoneView(TableViewBase viewBase) {
		super(TestPhoneTable.TYPES, viewBase);
	}

}
