/* This file was automatically generated by TightDB. */
package com.tightdb.test;

import com.tightdb.*;
import com.tightdb.lib.*;

/**
 * This class represents a TightDB query and was automatically generated.
 */
public class TestPhoneQuery extends AbstractQuery<TestPhoneQuery, TestPhoneRow, TestPhoneView> {

    public final StringQueryColumn<TestPhoneRow, TestPhoneView, TestPhoneQuery> type;
    public final StringQueryColumn<TestPhoneRow, TestPhoneView, TestPhoneQuery> number;
	public TestPhoneQuery(TableBase table, TableQuery query) {
		super(TestPhoneTable.TYPES, table, query);
        type = new StringQueryColumn<TestPhoneRow, TestPhoneView, TestPhoneQuery>(TestPhoneTable.TYPES, table, query, 0, "type");
        number = new StringQueryColumn<TestPhoneRow, TestPhoneView, TestPhoneQuery>(TestPhoneTable.TYPES, table, query, 1, "number");
	}

}
