/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_realm_SubtableSchema */

#ifndef _Included_com_realm_SubtableSchema
#define _Included_com_realm_SubtableSchema
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_realm_SubtableSchema
 * Method:    nativeAddColumn
 * Signature: (J[JILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_realm_SubtableSchema_nativeAddColumn
  (JNIEnv *, jobject, jlong, jlongArray, jint, jstring);

/*
 * Class:     com_realm_SubtableSchema
 * Method:    nativeRemoveColumn
 * Signature: (J[JJ)V
 */
JNIEXPORT void JNICALL Java_com_realm_SubtableSchema_nativeRemoveColumn
  (JNIEnv *, jobject, jlong, jlongArray, jlong);

/*
 * Class:     com_realm_SubtableSchema
 * Method:    nativeRenameColumn
 * Signature: (J[JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_realm_SubtableSchema_nativeRenameColumn
  (JNIEnv *, jobject, jlong, jlongArray, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
