/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_LinkView */

#ifndef _Included_io_realm_LinkView
#define _Included_io_realm_LinkView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_realm_LinkView
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_LinkView_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeGetRow
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_LinkView_nativeGetRow
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeGetTargetRowIndex
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_LinkView_nativeGetTargetRowIndex
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeAdd
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_LinkView_nativeAdd
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeInsert
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_LinkView_nativeInsert
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeSet
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_LinkView_nativeSet
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeMove
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_LinkView_nativeMove
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeRemove
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_realm_LinkView_nativeRemove
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeClear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_LinkView_nativeClear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_LinkView_nativeSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_realm_LinkView
 * Method:    nativeIsEmpty
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_LinkView_nativeIsEmpty
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
