package com.tightdb.example;

import java.io.IOException;
import java.util.Arrays;
import java.util.Date;

import com.tightdb.generated.Employee;
import com.tightdb.generated.EmployeeTable;
import com.tightdb.generated.EmployeeView;
import com.tightdb.generated.EmployeeQuery;
import com.tightdb.generated.Phone;
import com.tightdb.generated.PhoneTable;
import com.tightdb.generated.PhoneView;
import com.tightdb.generated.PhoneQuery;

import com.tightdb.lib.AbstractColumn;
import com.tightdb.lib.NestedTable;
import com.tightdb.lib.Table;
import com.tightdb.lib.TightDB;

import com.tightdb.Group;
import com.tightdb.TableBase;


public class Example {

	public static void main(String[] args) {
		
		showExample();
		
		//showSerialization();
		
		//Performance.TestJava();
	}
	
/******************************************************************/
/* Example of simple Tightdb operations using highlevel interface */
/******************************************************************/
	
	/* Define a table like below and name it in lowercase. 
	 * A class will be generated with first letter uppercase: Employee.
	 * Employee is a cursor to rows in the EmployeeTable, which will also be generated.
	 * The classes are generated by right-click tightdb-example, and select "Run As -> Maven generate-sources"
	 * Remember to save files before generating. And Refresh (F5) tightdb-example to see generated classes.
	 */
	
	@Table
	class employee {	
		String firstName;
		String lastName;
		int salary;
		boolean driver;
		byte[] photo;
		Date birthdate;
		Object extra;
		phone phones;
	}

	@NestedTable
	class phone {
		String type;
		String number;
	}

	static void showExample() {
		EmployeeTable employees = new EmployeeTable();

		/****************************** BASIC OPERATIONS *****************************/

		Employee john = employees.add("John", "Doe", 10000, true, new byte[] { 1, 2, 3 }, new Date(), "extra");
		Employee johny = employees.add("Johny", "Goe", 20000, true, new byte[] { 1, 2, 3 }, new Date(), true);
		Employee nikolche = employees.insert(1, "Nikolche", "Mihajlovski", 30000, false, new byte[] { 4, 5 }, new Date(), 1234.56);

		TightDB.print("Employees", employees);
		TightDB.print("Johny", johny);

		System.out.println("first record: " + john);
		System.out.println("second record: " + nikolche);
		System.out.println("some column: " + john.firstName);

		/****************************** GETTERS AND SETTERS *****************************/

		// 2 ways to get the value
		System.out.println("name1: " + john.firstName.get());
		System.out.println("name2: " + john.getFirstName());

		// 2 ways to set the value
		employees.at(2).lastName.set("NewName");
		employees.at(2).setLastName("NewName");

		Employee niko = employees.firstName.startsWith("Nik").findUnique();
		System.out.println("Unique Niko: " + niko);

		/****************************** MANIPULATION OF ALL RECORDS *****************************/

		// using explicit OR
		TightDB.print("Search example", employees.firstName.is("Johnny").or().lastName.is("Mihajlovski").findFirst());

		// using implicit AND
		TightDB.print("Search example 2", employees.firstName.is("Johnny").lastName.startsWith("B").findLast());

		employees.firstName.is("John").findLast().salary.set(30000);

		/****************************** ITERATION OF ALL RECORDS *****************************/

		// lazy iteration over the table
		for (Employee employee : employees) {
			System.out.println("iterating: " + employee);
		}

		/****************************** AGGREGATION *****************************/

		// aggregation of the salary (currently not implemented to return correct answer!)
		System.out.println("max salary: " + employees.salary.max());
		System.out.println("min salary: " + employees.salary.min());
		System.out.println("salary sum: " + employees.salary.sum());

		/****************************** COMPLEX QUERY *****************************/

		TightDB.print("Query 1", employees.firstName.startsWith("Nik").lastName.contains("vski").or().firstName.is("John").findAll());

		TightDB.print("Query 2a", employees.firstName.startsWith("Nik").startGroup().lastName.contains("vski").or().firstName.is("John").endGroup()
				.findAll());

		TightDB.print("Query 2b",
				employees.query().startGroup().lastName.contains("vski").or().firstName.is("John").endGroup().firstName.startsWith("Nik").findAll());

		/****************************** MANIPULATION OF ALL RECORDS *****************************/

		System.out.println("- First names: " + Arrays.toString(employees.firstName.getAll()));

		employees.salary.setAll(100000);
		employees.firstName.contains("o").findAll().firstName.setAll("Bill");

		TightDB.print(employees);

		/****************************** COLUMN RETRIEVAL *****************************/

		System.out.print("- Columns:");
		for (AbstractColumn<?, ?, ?> column : john.columns()) {
			System.out.print(column.getName() + "=" + column.getReadableValue());
		}
		System.out.println();

		/****************************** SUBTABLES *****************************/

		PhoneTable subtable = john.phones.get();
		subtable.add("mobile", "111");
		
		john.getPhones().add("mobile", "111");
		john.getPhones().add("home", "222");

		johny.getPhones().add("mobile", "333");

		nikolche.getPhones().add("mobile", "444");
		nikolche.getPhones().add("work", "555");

		for (PhoneTable phoneTable : employees.phones.getAll()) {
			TightDB.print(phoneTable);
		}

		/****************************** DATA REMOVAL *****************************/

		employees.remove(0);

		TightDB.print(employees);

		employees.clear();

		TightDB.print(employees);

		/****************************** NOT IMPLEMENTED YET *****************************/

		try {
			// from 2nd to 4th row
			EmployeeView view = employees.range(2, 4);

			// cursor navigation
			Employee p1 = employees.at(4).next(); // 5nd row
			Employee p2 = employees.last().previous(); // 2nd-last row
			Employee p3 = employees.first().after(3); // 4th row
			Employee p4 = employees.last().before(2); // 3rd-last row
		} catch (Exception e) {
		}
	}
	
	
	static void showSerialization() {
		// Create Table in Group
	    Group group = new Group();
	    TableBase t = group.getTable("people");
	    
	    // Add some rows by low-level interface - similar to highlevel and typesafe "add()"
	    t.insertString(	0, 0, "John");
	    t.insertLong(	1, 0, 20);
	    t.insertBoolean(2, 0, true);
	    t.insertDone();
	    
	    t.insertString(	0, 1, "Mary");
	    t.insertLong(	1, 1, 21);
	    t.insertBoolean(2, 1, false);
	    t.insertDone();
	    
	    t.insertString(	0, 2, "Lars");
	    t.insertLong(	1, 2, 21);
	    t.insertBoolean(2, 2, true);
	    t.insertDone();
	    
	    t.insertString(	0, 3, "Phil");
	    t.insertLong(	1, 3, 43);
	    t.insertBoolean(2, 3, false);
	    t.insertDone();
	    
	    // Write to disk
	    try {
			group.writeToFile("people.tightdb");
		} catch (IOException e) {
			e.printStackTrace();
		}
	    
	    // Load a group from disk (and print contents)
	    Group fromDisk = new Group();
	    fromDisk.load("people.tightdb");
	    
	    TableBase diskTable = fromDisk.getTable("people");
	    for (int i = 0; i < diskTable.getCount(); i++)
	        System.out.println(i + ": " + diskTable.getString(0, i) ); 	// print names
	    
	    // Write same group to memory buffer
	    byte[] buffer = group.writeToBuffer();
	    
	    // Load a group from memory (and print contents)
	    Group fromMem = new Group();
	    fromMem.loadData(buffer);	// method will be renamed to "loadMem"
	    TableBase memTable = fromMem.getTable("people");
	    for (int i = 0; i < memTable.getCount(); i++)
	    	System.out.println(i + ": " + memTable.getString(0, i) ); 	// print names
		
	}
}
