/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tightdb_TableViewBase */

#ifndef _Included_com_tightdb_TableViewBase
#define _Included_com_tightdb_TableViewBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeGetCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tightdb_TableViewBase_nativeGetCount
  (JNIEnv *, jobject);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeRemoveRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableViewBase_nativeRemoveRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeGetLong
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableViewBase_nativeGetLong
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeGetBoolean
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tightdb_TableViewBase_nativeGetBoolean
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeGetString
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tightdb_TableViewBase_nativeGetString
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeGetBinaryData
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tightdb_TableViewBase_nativeGetBinaryData
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeSetLong
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableViewBase_nativeSetLong
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeSetBoolean
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableViewBase_nativeSetBoolean
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeSetString
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableViewBase_nativeSetString
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeSetBinaryData
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableViewBase_nativeSetBinaryData
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeSum
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableViewBase_nativeSum
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeMax
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableViewBase_nativeMax
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    nativeMin
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableViewBase_nativeMin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tightdb_TableViewBase
 * Method:    createNativeTableView
 * Signature: (Lcom/tightdb/TableBase;)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableViewBase_createNativeTableView
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
