/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tightdb_TableBase */

#ifndef _Included_com_tightdb_TableBase
#define _Included_com_tightdb_TableBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeRegisterColumn
 * Signature: (Lcom/tightdb/ColumnType;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeRegisterColumn
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeGetString
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tightdb_TableBase_nativeGetString
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeGetLong
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableBase_nativeGetLong
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeGetBoolean
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tightdb_TableBase_nativeGetBoolean
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeGetBinaryData
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tightdb_TableBase_nativeGetBinaryData
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeGetColumnCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tightdb_TableBase_nativeGetColumnCount
  (JNIEnv *, jobject);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeGetColumnName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tightdb_TableBase_nativeGetColumnName
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeGetColumnType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tightdb_TableBase_nativeGetColumnType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeGetCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tightdb_TableBase_nativeGetCount
  (JNIEnv *, jobject);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeSetString
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeSetString
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeSetLong
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeSetLong
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeSetBoolean
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeSetBoolean
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeSetBinaryData
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeSetBinaryData
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeInsertString
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeInsertString
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeInsertLong
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeInsertLong
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeInsertBoolean
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeInsertBoolean
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeInsertBinaryData
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeInsertBinaryData
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeInsertDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeInsertDone
  (JNIEnv *, jobject);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeRemoveRow
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeRemoveRow
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tightdb_TableBase
 * Method:    nativeClear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_nativeClear
  (JNIEnv *, jobject);

/*
 * Class:     com_tightdb_TableBase
 * Method:    createNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableBase_createNative
  (JNIEnv *, jobject);

/*
 * Class:     com_tightdb_TableBase
 * Method:    executeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableBase_executeNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
