/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tightdb_SharedGroup */

#ifndef _Included_com_tightdb_SharedGroup
#define _Included_com_tightdb_SharedGroup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tightdb_SharedGroup
 * Method:    nativeGetDefaultReplicationDatabaseFileName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tightdb_SharedGroup_nativeGetDefaultReplicationDatabaseFileName
  (JNIEnv *, jclass);

/*
 * Class:     com_tightdb_SharedGroup
 * Method:    nativeHasChanged
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tightdb_SharedGroup_nativeHasChanged
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_SharedGroup
 * Method:    nativeBeginRead
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_SharedGroup_nativeBeginRead
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_SharedGroup
 * Method:    nativeEndRead
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_SharedGroup_nativeEndRead
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_SharedGroup
 * Method:    nativeBeginWrite
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_SharedGroup_nativeBeginWrite
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_SharedGroup
 * Method:    nativeCommit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_SharedGroup_nativeCommit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_SharedGroup
 * Method:    nativeRollback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_SharedGroup_nativeRollback
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_SharedGroup
 * Method:    createNative
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_SharedGroup_createNative
  (JNIEnv *, jobject, jstring, jint, jboolean, jboolean);

/*
 * Class:     com_tightdb_SharedGroup
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_SharedGroup_nativeClose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
