/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tightdb_TableView_Order */

#ifndef _Included_com_tightdb_TableView_Order
#define _Included_com_tightdb_TableView_Order
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
