/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tightdb_TableQuery */

#ifndef _Included_com_tightdb_TableQuery
#define _Included_com_tightdb_TableQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeValidateQuery
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tightdb_TableQuery_nativeValidateQuery
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeTableview
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeTableview
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeGroup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeEndGroup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeEndGroup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeSubtable
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeSubtable
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeParent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeParent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeOr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeOr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeEqual
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeEqual__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeNotEqual
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeNotEqual__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeGreater
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeGreater__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeGreaterEqual
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeGreaterEqual__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeLess
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeLess__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeLessEqual
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeLessEqual__JJJ
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeBetween
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeBetween__JJJJ
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeEqual
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeEqual__JJF
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeNotEqual
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeNotEqual__JJF
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeGreater
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeGreater__JJF
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeGreaterEqual
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeGreaterEqual__JJF
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeLess
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeLess__JJF
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeLessEqual
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeLessEqual__JJF
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeBetween
 * Signature: (JJFF)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeBetween__JJFF
  (JNIEnv *, jobject, jlong, jlong, jfloat, jfloat);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeEqual
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeEqual__JJD
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeNotEqual
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeNotEqual__JJD
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeGreater
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeGreater__JJD
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeGreaterEqual
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeGreaterEqual__JJD
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeLess
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeLess__JJD
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeLessEqual
 * Signature: (JJD)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeLessEqual__JJD
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeBetween
 * Signature: (JJDD)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeBetween__JJDD
  (JNIEnv *, jobject, jlong, jlong, jdouble, jdouble);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeEqual
 * Signature: (JJZ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeEqual__JJZ
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeEqualDateTime
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeEqualDateTime
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeNotEqualDateTime
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeNotEqualDateTime
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeGreaterDateTime
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeGreaterDateTime
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeGreaterEqualDateTime
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeGreaterEqualDateTime
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeLessDateTime
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeLessDateTime
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeLessEqualDateTime
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeLessEqualDateTime
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeBetweenDateTime
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeBetweenDateTime
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeEqual
 * Signature: (JJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeEqual__JJLjava_lang_String_2Z
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeNotEqual
 * Signature: (JJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeNotEqual__JJLjava_lang_String_2Z
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeBeginsWith
 * Signature: (JJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeBeginsWith
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeEndsWith
 * Signature: (JJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeEndsWith
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeContains
 * Signature: (JJLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_TableQuery_nativeContains
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeFind
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableQuery_nativeFind
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeFindAll
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableQuery_nativeFindAll
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeSumInt
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableQuery_nativeSumInt
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeMaximumInt
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableQuery_nativeMaximumInt
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeMinimumInt
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableQuery_nativeMinimumInt
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeAverageInt
 * Signature: (JJJJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_tightdb_TableQuery_nativeAverageInt
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeSumFloat
 * Signature: (JJJJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_tightdb_TableQuery_nativeSumFloat
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeMaximumFloat
 * Signature: (JJJJJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_tightdb_TableQuery_nativeMaximumFloat
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeMinimumFloat
 * Signature: (JJJJJ)F
 */
JNIEXPORT jfloat JNICALL Java_com_tightdb_TableQuery_nativeMinimumFloat
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeAverageFloat
 * Signature: (JJJJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_tightdb_TableQuery_nativeAverageFloat
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeSumDouble
 * Signature: (JJJJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_tightdb_TableQuery_nativeSumDouble
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeMaximumDouble
 * Signature: (JJJJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_tightdb_TableQuery_nativeMaximumDouble
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeMinimumDouble
 * Signature: (JJJJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_tightdb_TableQuery_nativeMinimumDouble
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeAverageDouble
 * Signature: (JJJJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_tightdb_TableQuery_nativeAverageDouble
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeMaximumDate
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableQuery_nativeMaximumDate
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeMinimumDate
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableQuery_nativeMinimumDate
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeCount
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableQuery_nativeCount
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_tightdb_TableQuery
 * Method:    nativeRemove
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_TableQuery_nativeRemove
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
