/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tightdb_Group */

#ifndef _Included_com_tightdb_Group
#define _Included_com_tightdb_Group
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tightdb_Group
 * Method:    createNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_Group_createNative__
  (JNIEnv *, jobject);

/*
 * Class:     com_tightdb_Group
 * Method:    createNative
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_Group_createNative__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_tightdb_Group
 * Method:    createNative
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_Group_createNative___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_tightdb_Group
 * Method:    createNative
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_Group_createNative__Ljava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_tightdb_Group
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_Group_nativeClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_Group
 * Method:    nativeGetTableCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_Group_nativeGetTableCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_Group
 * Method:    nativeHasTable
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tightdb_Group_nativeHasTable
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_tightdb_Group
 * Method:    nativeGetTableName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tightdb_Group_nativeGetTableName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_tightdb_Group
 * Method:    nativeGetTableNativePtr
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_Group_nativeGetTableNativePtr
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_tightdb_Group
 * Method:    nativeWriteToFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tightdb_Group_nativeWriteToFile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_tightdb_Group
 * Method:    nativeLoadFromMem
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_tightdb_Group_nativeLoadFromMem
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_tightdb_Group
 * Method:    nativeWriteToMem
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tightdb_Group_nativeWriteToMem
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_tightdb_Group
 * Method:    nativeWriteToByteBuffer
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_tightdb_Group_nativeWriteToByteBuffer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
