name: Issue Needs Attention
# This workflow is triggered on issue comments.
on:
  issue_comment:
    types: created

permissions: {}
jobs:
  applyNeedsAttentionLabel:
    permissions:
      issues: write # to remove and add labels
    uses: realm/ci-actions/.github/workflows/issue-needs-attention.yml@main
