name: Print Value

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Organization
        env:
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        run: |
          echo "Organization t Value: $AWS_S3_ACCESS_KEY_ID"
